language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: build
      script: mvn clean install
    - stage: deploy
      jdk: openjdk8
      if: tag IS present
      script: 'cp .ci-settings.xml $HOME/.m2/settings.xml && mvn clean deploy -DskipTests'

